# Generated by Django 2.2 on 2021-05-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthorsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='DEFAULT VALUE', max_length=255),
        ),
    ]
